name: Docker Build & Push to ECR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on:
  workflow_call:
    inputs:
      ecr_service_name:
        description: The ecs service name, which should also be the ecr repo name.
        required: true
        type: string
      ecs_service_name:
        description: The ecs service name, as defined by terraform.
        required: true
        type: string
      ecr_task_name:
        description: The ecs task definition name, which mayor may not be the same as the service name.
        required: true
        type: string
      ecr_cluster_name:
        description: The ecs cluster name.
        default: ecs-ue2-gui-core
        required: false
        type: string
      ecr_repo_name:
        description: The owner/name for the calling repository
        required: true
        type: string
      ecr_image_tag:
        description: The github sha for the calling workflow to tag the image
        required: true
        type: string

env:
  AWS_REGION: ${{ inputs.AWS_ECR_SERVER_REGION }}
  REGISTRY_URL: ${{ vars.AWS_ECR_SERVER_URL }}
  ECR_REPOSITORY: ${{ inputs.ecr_repo_name }}
  ECS_SERVICE: ${{ inputs.ecr_service_name }}
  ECS_FULL_SERVICE: ${{ inputs.ecs_service_name }}
  ECS_TASK_NAME: ${{ inputs.ecr_task_name }}
  ECS_CLUSTER: ${{ inputs.ecr_cluster_name }}
  ECS_IMAGE_TAG: ${{ inputs.ecr_image_tag }}
  # ECS_TASK_DEFINITION: ".aws/task-definition.json"
  # CONTAINER_NAME: MY_CONTAINER_NAME
  
jobs:
  build:
    name: Docker Build, Tag and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ vars.AWS_ECR_MASTER_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ECR_MASTER_SECRET }}
        aws-region: ${{ vars.AWS_ECR_SERVER_REGION }}
        soft_fail: true

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ inputs.ecr_image_tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json
        service: ${{ inputs.ecs_service_name }}
        cluster: ${{ inputs.ecr_cluster_name }}
        wait-for-service-stability: true    
  # tfsec:
  #   name: Security Checks
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: TFSec
  #     uses: aquasecurity/tfsec-action@v1.0.0
  #     with:
  #       soft_fail: true
  #       working_directory: ${{ inputs.terraform_working_directory }}
  #       version: ${{ env.TFSEC_VERSION }}
        
  # checkov:
  #   name: Policy Checks
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Checkov
  #     uses: bridgecrewio/checkov-action@master
  #     with:
  #       quiet: false
  #       soft_fail: false
  #       directory: ${{ inputs.terraform_working_directory }}
  #       skip_check: CKV_TF_1
  #       framework: terraform
  #       output_format: sarif
  #       download_external_modules: false
  #       log_level: WARNING
        
  # terraform:
  #   needs: [tflint, tfsec, checkov]
  #   name: Terraform Validation
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Terraform - Setup
  #     uses: hashicorp/setup-terraform@v2
  #     with: 
  #       terraform_version: ${{ env.TFC_VERSION }}
  #       cli_config_credentials_hostname: ${{ secrets.TFC_ADDR }}
  #       cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

  #   - name: Terraform - Init
  #     working-directory: ${{ inputs.terraform_working_directory }}
  #     run: terraform init

  #   - name: Terraform - Validate
  #     working-directory: ${{ inputs.terraform_working_directory }}
  #     run: terraform validate -no-color
      
  #   - name: Terraform - Speculative Plan
  #     if: ${{ inputs.module_level == 4 }}
  #     working-directory: ${{ inputs.terraform_working_directory }}
  #     run: terraform plan

  # documentation:
  #   if: ${{ inputs.module_level != 4 }}
  #   name: Documentation
  #   needs: [tflint, tfsec, checkov]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Render Documentation
  #     uses: terraform-docs/gh-actions@main
  #     with:
  #       output-method: replace
  #       git-push: "true"
  #       working-dir: ${{ inputs.terraform_working_directory }}
